from datetime import date
from datetime import datetime
from uuid import UUID

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from pydantic import model_validator


class RecommendationCreate(BaseModel):
    """
    Schema for creating an AI-generated recommendation.
    """

    destination: str = Field(
        ...,
        min_length=2,
        max_length=255,
        description="Recommended travel destination.",
        examples=["Goa"],
    )

    recommended_start_date: date = Field(
        description="Recommended trip start date.",
    )

    recommended_end_date: date = Field(
        description="Recommended trip end date.",
    )

    reason: str = Field(
        ...,
        max_length=2000,
        description="Reason generated by the AI for recommending this destination.",
        examples=[
            "Goa matches the group's budget, preferred climate, and activities."
        ],
    )

    estimated_cost: float = Field(
        ...,
        gt=0,
        description="Estimated cost per person in INR.",
        examples=[18000.0],
    )

    confidence_score: float = Field(
        ...,
        ge=0,
        le=1,
        description="Confidence score assigned by the AI model.",
        examples=[0.92],
    )

    model_provider: str = Field(
        ...,
        min_length=2,
        max_length=255,
        description="AI model provider.",
        examples=["Ollama"],
    )

    model_name: str = Field(
        ...,
        min_length=2,
        max_length=255,
        description="Name of the AI model used.",
        examples=["llama3.2"],
    )

    prompt_version: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Version of the prompt template used.",
        examples=["v1"],
    )

    @model_validator(mode="after")
    def validate_date_range(self):
        """
        Ensure the recommended date range is valid.
        """

        if self.recommended_start_date > self.recommended_end_date:
            raise ValueError(
                "recommended_start_date must be before or equal to recommended_end_date."
            )

        return self


class RecommendationUpdate(BaseModel):
    """
    Schema for updating an AI recommendation.
    """

    destination: str | None = Field(
        default=None,
        min_length=2,
        max_length=255,
        description="Updated travel destination.",
    )

    recommended_start_date: date | None = Field(
        default=None,
        description="Updated recommended trip start date.",
    )

    recommended_end_date: date | None = Field(
        default=None,
        description="Updated recommended trip end date.",
    )

    reason: str | None = Field(
        default=None,
        max_length=2000,
        description="Updated recommendation reason.",
    )

    estimated_cost: float | None = Field(
        default=None,
        gt=0,
        description="Updated estimated cost per person.",
    )

    confidence_score: float | None = Field(
        default=None,
        ge=0,
        le=1,
        description="Updated confidence score.",
    )

    model_provider: str | None = Field(
        default=None,
        min_length=2,
        max_length=255,
        description="Updated AI model provider.",
    )

    model_name: str | None = Field(
        default=None,
        min_length=2,
        max_length=255,
        description="Updated AI model name.",
    )

    prompt_version: str | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        description="Updated prompt version.",
    )

    @model_validator(mode="after")
    def validate_date_range(self):
        """
        Validate the date range only when both dates are provided.
        """

        if (
            self.recommended_start_date is not None
            and self.recommended_end_date is not None
            and self.recommended_start_date > self.recommended_end_date
        ):
            raise ValueError(
                "recommended_start_date must be before or equal to recommended_end_date."
            )

        return self


class RecommendationResponse(BaseModel):
    """
    Schema returned when sending recommendation data.
    """

    model_config = ConfigDict(
        from_attributes=True,
    )

    id: UUID = Field(
        description="Unique identifier of the recommendation.",
    )

    trip_id: UUID = Field(
        description="Trip associated with this recommendation.",
    )

    destination: str = Field(
        description="Recommended travel destination.",
    )

    recommended_start_date: date = Field(
        description="Recommended trip start date.",
    )

    recommended_end_date: date = Field(
        description="Recommended trip end date.",
    )

    reason: str = Field(
        description="Reason for the recommendation.",
    )

    estimated_cost: float = Field(
        description="Estimated cost per person in INR.",
    )

    confidence_score: float = Field(
        description="Confidence score generated by the AI model.",
    )

    model_provider: str = Field(
        description="AI model provider.",
    )

    model_name: str = Field(
        description="AI model name.",
    )

    prompt_version: str = Field(
        description="Prompt template version.",
    )

    created_at: datetime = Field(
        description="Timestamp when the recommendation was created.",
    )