from uuid import UUID
from sqlalchemy.orm import Session
from app.models.recommendation import Recommendation

class RecommendationRepository:
    """Repository responsible for Recommendation database operations."""

    def __init__(self,db: Session,) -> None:
        self.db = db

    def create(self,recommendation: Recommendation) -> Recommendation:
        """Create a new recommendation."""
        try:
            self.db.add(recommendation)
            self.db.flush()
            self.db.refresh(recommendation)
            return recommendation
        except Exception:
            self.db.rollback()
            raise

    def get_by_id(self,recommendation_id: UUID) -> Recommendation | None:
        """Retrieve a recommendation by its unique identifier."""
        return self.db.get(Recommendation,recommendation_id)

    def get_all(
        self,
    ) -> list[Recommendation]:
        """
        Retrieve all recommendations.
        """

        return (
            self.db.query(
                Recommendation,
            )
            .all()
        )

    def update(
        self,
        recommendation: Recommendation,
    ) -> Recommendation:
        """
        Update an existing recommendation.
        """

        try:

            self.db.flush()

            self.db.refresh(
                recommendation,
            )

            return recommendation

        except Exception:

            self.db.rollback()

            raise

    def save(
        self,
        recommendation: Recommendation,
    ) -> Recommendation:
        """
        Persist recommendation changes.
        """

        try:

            self.db.flush()

            self.db.refresh(
                recommendation,
            )

            return recommendation

        except Exception:

            self.db.rollback()

            raise

    def delete(
        self,
        recommendation_id: UUID,
    ) -> bool:
        """
        Delete a recommendation.

        Returns:
            True if the recommendation was deleted.
            False otherwise.
        """

        recommendation = self.get_by_id(
            recommendation_id,
        )

        if recommendation is None:

            return False

        try:

            self.db.delete(
                recommendation,
            )

            self.db.flush()

            return True

        except Exception:

            self.db.rollback()

            raise

    def exists(
        self,
        recommendation_id: UUID,
    ) -> bool:
        """
        Check whether a recommendation exists.
        """

        return (
            self.db.get(
                Recommendation,
                recommendation_id,
            )
            is not None
        )

    def get_by_trip_id(
        self,
        trip_id: UUID,
    ) -> list[Recommendation]:
        """
        Retrieve all recommendations for a trip.
        """

        return (
            self.db.query(
                Recommendation,
            )
            .filter(
                Recommendation.trip_id == trip_id,
            )
            .all()
        )

    def get_by_model(
        self,
        model_name: str,
    ) -> list[Recommendation]:
        """
        Retrieve recommendations generated by a model.
        """

        return (
            self.db.query(
                Recommendation,
            )
            .filter(
                Recommendation.model_name == model_name,
            )
            .all()
        )

    def get_by_prompt_version(
        self,
        prompt_version: str,
    ) -> list[Recommendation]:
        """
        Retrieve recommendations generated using
        a specific prompt version.
        """

        return (
            self.db.query(
                Recommendation,
            )
            .filter(
                Recommendation.prompt_version == prompt_version,
            )
            .all()
        )
    def delete_by_trip_id(
        self,
        trip_id: UUID,
    ) -> None:
        """
        Delete all recommendations for a trip.
        """

        (
            self.db.query(
                Recommendation,
            )
            .filter(
                Recommendation.trip_id == trip_id,
            )
            .delete(
                synchronize_session=False,
            )
        )
    def get_best_recommendation(
        self,
        trip_id: UUID,
    ) -> Recommendation | None:
        """
        Retrieve the recommendation with the highest confidence score.
        """

        return (
            self.db.query(
                Recommendation,
            )
            .filter(
                Recommendation.trip_id == trip_id,
            )
            .order_by(
                Recommendation.confidence_score.desc(),
            )
            .first()
        )
